### ISSUE TITLE
Code availability

### ISSUE THREAD

**Issue by pravn** [YunseokJANG/amc-gan#1]
Brilliant work. Updates on code availability?

**Comment by YunseokJANG** [comment]
Hi @pravn. 
First of all, thank you for your interest in our work and sorry for the delay.

I was supposed to upload right after the conference, but I wasn't able to do that because I lost my checked bag which contains an external hard drive with code segments (not by my mistake, but by the airline), on the way to go back to my house from the conference. I need to inspect which items are missing and will release the code, first. However, because of my hectic schedules, I wasn't able to spend time on this. Right now, I am thinking of uploading the code in sometime in May (I also want to share it before I start a new one). But again, sorry for the delay and thanks for your interest.

Regards,
- Yunseok

**Comment by pravn** [comment]
Hi Yunseok
Thanks for the reply. Looking forward to the upload.
Praveen.

pravn.wordpress.com
